### ISSUE TITLE
[Cadastro Aluna] Não é possível concluir cadastro sem campos opcionais preenchidos

### ISSUE THREAD

**Issue by camipuchta-tw** [MeConta/me-conta#10]
Não é possível concluir cadastro de aluna sem preencher os campos opcionais

**Steps para reprodução:**
1- Acessar https://me-conta-frontend.herokuapp.com/cadastro-aluno
2- Preencher todos os campos obrigatórios
3- Deixar os campos "Quais são suas necessidades no momento?", "O que você espera de nosso serviço?" e "Você já fez algum tipo de tratamento psicológico?" em branco e clicar em "Concluir minha inscrição"

**Resultado atual**
Mensagem "Erro ao realizar o cadastro!" é exibida (evidência em anexo)

**Resultado esperado**
Cadastro realizado com sucesso

https://user-images.githubusercontent.com/94621889/142642638-d290a9b6-5b4b-463b-a106-889d02a353d6.mov

**Comment by camipuchta-tw** [comment]
https://trello.com/c/gKnD4sQJ/39-cadastro-aluna-campos-faltantes

**Comment by camipuchta-tw** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[cadastro aluna] - campos faltantes](https://trello.com/c/gKnD4sQJ/39-cadastro-aluna-campos-faltantes)

**Comment by camipuchta-tw** [comment]
https://user-images.githubusercontent.com/94621889/142642144-d2b89394-d222-425e-8e98-503a468adba3.mov

**Comment by Dihgg** [comment]
O frontend está mandando:
`
  {
      ...
      "necessidades": "",
      "expectativas": "",
      "tratamentos": ""
  }
`
O backend aceita esses valores como nulos, mas não aceita strings vazias
