### ISSUE TITLE
[Criar Conta] - Senha não está atendendo os requisitos mínimos

### ISSUE THREAD

**Issue by fracassogiovanna** [MeConta/me-conta#15]
Steps para reprodução

Dado que estou na página de criação de conta https://me-conta-frontend.herokuapp.com/criar-conta

1 - Preencher campos de preenchimento obrigatório
2 - Preencher o campo senha e confirmar senha com **meconta1234**
3 - Selecionar termos e condiçoes
4 - Clicar no botão cadastrar

**Resultado atual:**
Então é possível ir para o próximo formulário

**Resultado esperado:**
Então deverá exibir a mensagem: A senha deve conter Mínimo de 8 caracteres
Pelo menos 1 letra maiúscula
Pelo menos 1 letra minúscula
Pelo menos 1 caractere especial
Pelo menos 1 número
E não deixar ir para o próximo formulário

https://user-images.githubusercontent.com/93267750/146204678-25947cc4-7ff0-4f99-b1a7-0719668ece7e.mov

**Comment by Dihgg** [comment]
A senha utiliza uma biblioteca de entropia chamada [zxcvbnm](https://github.com/dropbox/zxcvbn) tanto no back quanto no frontend.
Essa biblioteca não utiliza limitadores como "deve possuir um carácter" mas dá uma "nota" para sua senha.

O que dá para fazer é exigir uma nota mais alta.

**Comment by fracassogiovanna** [comment]
Foi alinhado com o time de que nesse momento vamos manter a forma como está, sendo necessário apenas números e letras, e no futuro se for necessário para o negócio será implementado para ter uma senha mais forte
