### ISSUE TITLE
[Login] - Perfil de atendente e supervisor são direcionados para página de aluna

### ISSUE THREAD

**Issue by fracassogiovanna** [MeConta/me-conta#20]
Dado que possua usuário criado para o perfil de voluntária atendente / supervisor

Steps para reproduzir
1- preencher campos email e senha
2- clicar no botão Entrar

**Resultado atual:**
Então sou direcionada para a url [https://me-conta-frontend.herokuapp.com/dashboard-aluno](url)

**Resultado esperado:**
Então deverá ser redirecionado para página da voluntária

https://user-images.githubusercontent.com/93267750/146444039-991a1100-4661-47f9-a533-c774b1e345b9.mov

**Comment by alexandreramires** [comment]
Fazer última revisão.

**Comment by alexandreramires** [comment]
Corrigido.
