### ISSUE TITLE
Fazer levantamento do Servidor

### ISSUE THREAD

**Issue by temonteiro** [MeConta/me-conta#4]
Fazer um levantamento dos melhores servidores de hospedagem pensando no custo/benefício bem como nas tecnologias que escolhemos utilizar nesse projeto.

**Comment by Dihgg** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fazer levantamento do Servidor](https://trello.com/c/U4XUYXnk/49-fazer-levantamento-do-servidor)

**Comment by temonteiro** [comment]
Estou fazendo o levantamento de alguns site para marcar uma reunião para conversar melhor sobre servidores:

 - https://www.digitalocean.com/pricing/
    - https://www.digitalocean.com/community/tutorials/como-construir-imagens-docker-e-hospedar-um-repositorio-de-imagens-docker-com-o-gitlab-pt
 - https://king.host/node-js
 - https://www.hostgator.com.br/hospedagem-de-sites
 - https://aws.amazon.com/pt/docker/
 - https://www.hostinger.com.br/servidor-vps
 - https://www.umbler.com/br/hospedagem-de-sites

**Comment by Dihgg** [comment]
- Ficamos entre o king Host e a Hostinger
- A @temonteiro  tirará dúvidas com os servidores para saber se eles irão atender nossas necessidades:
    - Docker
    - Banco de dados (postgres)
    - E-mail

**Comment by temonteiro** [comment]
**Sobre o plano VPS da Kinghost:**
O plano de VPS não é estruturado igual aos plano de hospedagem, é um servidor dedicado onde o cliente gerencia desde a instalação do sistema operacional até a instalação e gerenciamento das aplicações que deseja executar nele, não terá nada pré instalado nele, tudo é o cliente quem instala e gerencia, a Kinghost disponibiliza a estrutura do servidor para você poder usar, mas não estruturamos nada nele, e *não contempla serviço para e-mails*, se desejar terá que manter o plano de hospedagem para os e-mails.

Seguem as orientações quando ao suporte que prestamos ao VPS: 

- Ativação do ambiente (se funcionou ou não); 
- Reboot da máquina virtual;
- Funcionalidade das ferramentas disponíveis no Painel de Controle;
- Gerenciar DNS (ferramenta do painel de controle);
- Remoção e criação de novo ambiente.

Não fornecemos suporte: qualquer configuração dentro da VPS, como instalação de algum serviço, servidor, etc. 
Nem migração das aplicações.
Tudo que for realizado dentro do sistema operacional do VPS não teremos como dar suporte.


Valor do servidor: R$ 27.90
Servidor de e-mail: 21.34
Total: 49.24

**Comment by temonteiro** [comment]
### Sobre o plano VPS da Hostinger:

Olha, a VPS é a sigla para Virtual Private Server, ou Servidor Virtual Privado, como é chamado em português, e pode ser definido como um espaço 'isolado' (servidor virtual) dentro de um servidor físico.

Cada servidor virtual (container) funciona exatamente como um servidor dedicado, apesar de possuir capacidade de processamento menor, podendo manter seus próprios scripts, usuários, processos, arquivos, softwares etc.


﻿Nas nossas VPS podes sim utilizar Docker, banco de dados Postgre e o serviço de e-mail também é incluso , eba! 🤩
﻿
﻿Olha, separei os artigos para te ajudar
﻿
﻿[DOCKER](https://www.hostinger.com.br/tutoriais/install-docker-ubuntu)
﻿
﻿[POSTGREE](https://www.hostinger.com.br/tutoriais/instalar-postgresql-ubuntu)
﻿
[﻿EMAIL NA VPS](https://www.hostinger.com.br/tutoriais/como-instalar-configurar-servidor-de-email-ubuntu)


﻿O gerenciamento individual dos recursos permite garantir memória RAM, CPU e espaço em disco para cada VPS. Isso significa que, independentemente do que o servidor virtual "ao lado" esteja processando, não haverá interferência na performance do seu.
Plano mensal:
![image](https://user-images.githubusercontent.com/1629392/129367047-8c42de7f-67df-4e31-8fc7-392e03d74dc2.png)

**Comment by temonteiro** [comment]
Finalizei o documento pra ser enviado para Valentina.

**Comment by temonteiro** [comment]
Finalizei o documento para enviar para a Valentina
