### ISSUE TITLE
Banco de dados WIX

### ISSUE THREAD

**Issue by temonteiro** [MeConta/me-conta#5]
Acessar a plataforma do Wix e descobrir as informações sobre o banco de dados da aplicação. Verificar se é possível exportar esses dados e quais são as informações que são armazenadas que podemos utilizar em nosso projeto.

**Comment by Dihgg** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Banco de dados WIX](https://trello.com/c/T80yUrKc/50-banco-de-dados-wix)

**Comment by temonteiro** [comment]
Carlos já conseguiu o acesso ao Wix e descobriu como recuperar essas informações
